osx_image: xcode8
language: generic
matrix:
  include:
    - os: osx
      env:
        - PLATFORM=macos
        - XCODE_ACTION="build-for-testing test-without-building"
    - os: osx
      env:
        - PLATFORM=ios
        - XCODE_ACTION="build-for-testing test-without-building"
    - os: osx
      env:
        - PLATFORM=tvos
        - XCODE_ACTION="build-for-testing test-without-building"
    - os: osx
      sudo: required
      env:
        - PODSPEC=1
    - os: linux
      sudo: required
      dist: trusty
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ./script/travis-install-macos; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./script/travis-install-linux; fi
  - if [[ "$PODSPEC" ]]; then rvm system; sudo gem install bundler; bundle install; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ./script/travis-script-macos; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./script/travis-script-linux; fi
