name: CI (SwiftPM)

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          paths: '[".github/workflows/ci-swiftpm.yml", "Sources/**", "Tests/**", "Package.*"]'
          do_not_skip: '["push", "workflow_dispatch", "schedule"]'

  swiftpm_darwin:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    needs: filter
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [11.7, 12.4]
      fail-fast: false
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app"
    steps:
      - uses: actions/checkout@v2
        if: ${{ needs.filter.outputs.should_skip != 'true' }}
      - run: rake test:swiftpm
        if: ${{ needs.filter.outputs.should_skip != 'true' }}

  swiftpm_linux:
    name: SwiftPM, Linux
    needs: filter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - swift:5.2
          - swift:5.3
          - swift:5.4
          - swiftlang/swift:nightly
      fail-fast: false
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
        if: ${{ needs.filter.outputs.should_skip != 'true' }}
      - run: swift build -Xswiftc -suppress-warnings
        if: ${{ needs.filter.outputs.should_skip != 'true' }}
      - run: swift test -Xswiftc -suppress-warnings
        if: ${{ needs.filter.outputs.should_skip != 'true' }}
