name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  xcode:
    name: Xcode ${{ matrix.xcode }}
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: [11, 11.1, 11.2, 11.3]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
    - run: PLATFORM=macos ./script/travis-script-macos
    - run: PLATFORM=macos_static ./script/travis-script-macos
    - run: PLATFORM=ios ./script/travis-script-macos
    - run: PLATFORM=tvos ./script/travis-script-macos

  swiftpm_darwin:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: [11, 11.1, 11.2, 11.3]
    steps:
    - uses: actions/checkout@v1
    - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
    - run: PLATFORM=swiftpm ./script/travis-script-macos
